name: Deploy React Vite App to Vercel

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: Build and Deploy to Vercel
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: react-app/package-lock.json

      - name: 3. Install Dependencies
        run: npm install
        working-directory: react-app

      - name: 4. Build Project
        run: npm run build
        working-directory: react-app
        env:
          NODE_ENV: production

      - name: 5. Pull Vercel Environment Information
        run: npx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: 6. Deploy Project to Vercel
        run: npx vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}